### ISSUE TITLE
Etapa 06, nome do vídeo: Eventos do teclado - Aula 02-03

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1932]
Roger, eu ia te mandar uma dúvida falando que o evento `keyup`nao estava mudando de cor, mas depois eu tive uma idéia de aumentar o stroke (pra 7px) da borda e percebi que está mudando sim, mas ficava um preto por cima e por isso eu nao estava vendo.
Mas depois que eu clico em qualquer outro lugar, o preto some e da pra ver que mudou, mas so depois de clicar em qualquer outro lugar do browser. 

Gostaria de saber pq minha borda está preta e a sua do exemplo do vídeo não.
E pq depois q eu clico em outro lugar o a borda preta some.

```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./style.css">

    <title>O evento submit</title>
</head>

<body>
    <h1>O evento submit</h1>
    <form class="signup-form">
        <input type="text" id="username" placeholder="username" autofocus>
        <p class="feedback"></p>
        <button>Enviar</button>
    </form>
    <script src="./app.js"></script>

</body>

</html> 
```

```css
body{
    background:#eee;
}

h1{
    text-align: center;
}

form{
    max-width:200px;
    margin:40px auto;
    background:white;
    padding:10px;
}

input,button{
    display:block;
    margin:10px auto;
    padding:4px;
} 

.success{
    border:7px solid green;
}

.fail{
    border:7px solid red;
}
```
Antes de clicar em outro lugar, imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/136682536-69dc59f0-33f9-436d-9785-8814d7eed4b9.png)

Depois de clicar em qualquer outro lugar, imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/136682606-f9e8d2b9-7ff1-4b0b-9ec5-ed7bc79a7933.png)

Aumentei o stroke para 7px, talvez melhore o entendimento.

Antes de clicar em qualquer outro lugar, imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/136682682-f3a4a652-44fb-4182-bce1-eb7a77570f3e.png)

Depois de clicar em qualquer outro lugar, imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/136682712-7fd05526-6098-44bc-bef1-0cea8f420349.png)

borda padrão antes de dar o input, imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/136682758-05e8ae4e-f676-4a5e-b6ea-d789865e29e8.png)

@Roger-Melo
