### ISSUE TITLE
Resumo da Aula Eventos do teclado - Aula 02-03 da etapa 06

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#1997]
# Eventos do teclado - Aula 02-03

* Evento keyup: Executa uma função de *callback* toda vez a tecla pressionada for liberada(isso quando o foco estiver em algum *input* do *form* onde o evento é ouvido). Esse evento pode ser aplicado para fazer uma checagem de *regex* em tempo real como mostrado no código abaixo no qual a não satisfação da *regex* é sinalizada com a cor vermelha do *input* :

* JavaScript
```js
/**
    - De 6 a 12 caracteres.
    - Letras.
		 ||
		\  /
		 \/
		 
    /^[a-zA-Z]{6,12}$/
 */

const form = document.querySelector('form');
const pattern =  /^[a-zA-Z]{6,12}$/;
const feedback = document.querySelector('.feedback')


form.addEventListener('keyup', event =>{
    
    const input = event.target;
    console.log(input.value.length);
    const isMatch = pattern.test(input.value);

    if(!isMatch){
        input.setAttribute('class','noMatch');//input.classList.add('noMatch');
    }else{
        input.removeAttribute('class','noMatch');//input.classList.remove('noMatch');
    }
})
```
* HTML
```HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./style.css">
    <title>Testando Expressões regulares</title>
</head>
<body>
    <div class="title">
        <h1>Testando padrões regex em tempo real</h1>
    </div>

    <div class="form">
        <form>
            <input type="text" id="username" name="name" placeholder="username">
            <button>Enviar</button>
        </form>
    </div>

    <script src="./script.js"></script>
</body>
</html>
```
* CSS
```css
h1{
    color: rgb(204, 204, 204);
}

body{
    background-color: rgb(30, 30, 30);
}

.title{
    height: 80px;
    text-align: center;
    
}

.form{
    margin: auto;
    padding-top: 50px;
    height: 100px;
    width: 200px;
    background-color: rgb(45, 45, 45);
    text-align: center;
}

input{
    margin: 5px;
}

.feedback{
    color: rgb(204, 204, 204);
    font-size: 70%;
}

.noMatch{
    background-color: rgba(231, 7, 7, 0.486);
    border-color:rgba(231, 7, 7, 0.486) ;
}
```

@Roger-Melo
