### ISSUE TITLE
problema visual com o evento 'keyup'

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2487]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/927205

### Descreva a dúvida

basicamente tive um problema com a resposta da mudança de classe CSS do form. 
```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testeUsername = username => /^[a-zA-Z]{6,12}$/.test(username)

form.addEventListener('submit', event => {
    event.preventDefault()
    
    const username = event.target.username.value
    const isAValidName = testeUsername(username)

    if(isAValidName){
        feedback.textContent = 'Username válido =)'
        return    
    }

    feedback.textContent = `o username deve conter entre 
    6 a 12 caracteres e deve conter apenas letras`
}) 

form.username.addEventListener('keyup', event => {
    const username = event.target.value
    const isAValidUsername = testeUsername(username)

    if(isAValidUsername) {
        form.username.setAttribute('class', 'sucess')
        return    
    }
    form.username.setAttribute('class', 'error') 
})
```
**quando eu escrevo algo na barra do form, ele não muda de cor, somente quando eu clico com o cursor em outra área da pagina que a mudança de cor ocorre**

![input(1)](https://user-images.githubusercontent.com/85198581/146082839-1790f588-993b-406c-8fc4-09b40a294475.jpg)
![input(2)](https://user-images.githubusercontent.com/85198581/146082846-057183f9-ca5d-4e4b-a53c-c83ce3e7a88c.jpg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

Vc pode postar o código completo (incluindo HTML e CSS)?

Assim fica mais fácil eu testar aqui e ajudar =)

**Comment by CarlosHenrique2208** [comment]
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Testes</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <h1>O evento submit</h1>

    <form class="signup-form">
        <input type="text" id="username" placeholder="username" autofocus>
        <button>Enviar</button>
        <p class="feedback"></p>
    </form>
    
    <!-- http://127.0.0.1:5501/index.html -->
    <script src="./app.js"></script>
</body>
</html>
```

```css
body {
    background: #eee;
}

h1 {
    text-align: center;
}

form {
    max-width: 200px;
    margin: 40px auto;
    background: white;
    padding: 10px;
}

input, button {
    display: block;
    margin: 10px auto;
    padding: 4px;
}

.succes {
    border: 2px solid green;
}

.error {
    border: 2px solid red;
}
```
perdão a demora pra responder...
