### ISSUE TITLE
Ainda sobre a dúvida passada

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2762]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/927205

### Descreva a dúvida

```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testUsername = username => /^[a-zA-z]{6,12}$/.test(username)

form.addEventListener('submit', event => {
  event.preventDefault()

  const isAvalidUsername = testUsername(event.target.username.value)

  if (isAvalidUsername) {
    feedback.textContent = 'Username válido =)'
    return
  }
  feedback.textContent = 'o username deve conter entre 6 e 12 caracteres e deve conter apenas letras'
})
form.username.addEventListener('keyup', event => {
  const isAvalidUsername = testUsername(event.target.username)
  console.log(event.target.username)
  
   if (isAvalidUsername) {
      form.username.setAttribute('class', 'success')
      return
   }
   form.username.setAttribute('class', 'error')
})
})
```
```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>Eventos de teclado</title>
</head>

<body>
  <h1>Eventos de teclado</h1>
  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
    <p class="feedback"></p>
  </form>
  <script src="./app.js"></script>
</body>

</html>
```

```css
body {
  background: #eee;
}

h1 {
  text-align: center;
}

form {
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}

.success {
  border: 2px solid green;
}

.error {
  border: 2px solid red;
}
```

```js
form.username.addEventListener('keyup', event => {
  const isAvalidUsername = testUsername(event.target.username)
  console.log(event.target.username) //undefined
//...
})
```

Roger, porque que na aula deu certo e quando escrevi aqui esse trecho da undefined?

@Roger-Melo
