### ISSUE TITLE
Exercícios da aula 02 da etapa 06 

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#2998]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/943413

### Descreva a dúvida

Resolvi usar os aprendizados das aulas para criar um formulário e através do JavaScript  auxiliar o usuário a completar um formulário para cadastrar uma conta, eis aqui o código:

**HTML**
```html
 <div class="container">
    <div class="form-container">
      <div class="form-content">
        <h2>Crie sua conta</h2>
        <form action="#">
          <input type="text" name="name" id="name" placeholder="Nome completo" autocomplete="off" required>
          <input type="email" name="email" id="email" placeholder="Email" required>
          <div id="password-container"><input type="password" name="password" id="password" placeholder="Senha" required><a href="#" class="password-eye"><svg stroke="currentColor" fill="#202124" stroke-width="0" viewBox="0 0 24 24" height="1rem" width="1rem" xmlns="http://www.w3.org/2000/svg"><path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"></path></svg></a></div>
          <div id="password-container">
            <input type="password" name="password" id="password-confirm" placeholder="Confirmar" required>
            <a href="#" class="password-eye">
              <svg stroke="currentColor" fill="#202124" stroke-width="0" viewBox="0 0 24 24" height="1rem" width="1rem" xmlns="http://www.w3.org/2000/svg"><path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"></path></svg>
            </a>
          </div>
          <p class="terms">Ao criar sua conta você concorda com nossos <a href="#">termos de uso</a> e <a href="#">política de privacidade</a>.</p>
          <div class="button-container">
            <button class="btn-secundary">Ja sou cadastrado</button>
            <button type="submit">Criar conta</button>
          </div>
        </form>
      </div>
    </div>
  </div>
```

CSS
```css
div, input, p{
  padding: 0;
  margin: 0;
  box-sizing: border-box;
  font-family: Arial, Helvetica, sans-serif;
}

input{
  display: block;
  width: 100%;
  height: 48px;
  margin-top: 20px;
  padding: 0 8px;

  font-size: 15px;
  color: #202124;
  border-radius: 4px;
  border: 1px solid #202124;
  letter-spacing: 0.25px;
  background-color: transparent;

  appearance: none;
}

input:focus{
  background: #1f18a715;
  border: 2px solid #1E18A7;
  outline: #1E18A7;
}

.button-container{
  display: flex;
  width: 100%;
  justify-content: space-between;
  margin-top: 40px;
}

button{
  width: 100%;
  height: 48px;

  font-size: 16px;
  font-weight: bold;
  color: #FFFFFF;
  border-radius: 4px;
  background: #1E18A7;
  border: 0;
}

.btn-secundary{
  display: inline-block;
  width: 100%;
  padding: 0;
  margin: 0;

  font-size: 15px;
  font-weight: 500;
  color: #1E18A7;
  text-align: start;
  text-decoration: underline;
  background: none;
  appearance: none;
}

.error-message{
  width: 100%;
  padding: 8px 0;
  display: grid;
  align-items: flex-start;
  gap: 8px;
  grid-template-columns: 20px 1fr;

  margin: 0px 0 16px 0px;
}

.icon-error{
  display: block;

}

.name-error {
  color: red;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.5px;
  display: inline-block;
}

.name-error:focus {
  border: 2px solid red;
}


a{
  text-decoration: none;
  color: #1E18A7;
}

.container{
  display: flex;
  justify-content: center;
  align-items: center;
}

.form-container{
  width: 100%;
  max-width: 414px;
  padding: 20px;
}

#password-container{
  width: 100%;
  height: 100%;

  position: relative;
  margin-top: 16px;
  border-radius: 4px;
}

#password-container svg {
  position: absolute;
  right: 0;
  top: 4px;
  padding: 12px;
  cursor: pointer;
}

.terms{
  line-height: 24px;
  margin: 24px 0;
  /* text-align: center; */
}
```

JS
```js
const form = document.querySelector('form')
const inputName = document.querySelector('#name')
const inputEmail = document.querySelector('#email')
const inputPassword = document.querySelector('#password')
const inputConfirmPassword = document.querySelector('#password-confirm')

const passwordContainer = document.querySelector('#password-container')
const passwordEye = document.querySelectorAll('.password-eye')

const div = document.createElement('div')
const p = document.createElement('p')
const icon = document.createElement('svg')

const nameRules = event => {
  const inputValue = event.target.value
  const nameRegex = /^[a-zA-Z ]{2,}$/

  if (!nameRegex.test(inputValue)) {
    event.target.insertAdjacentElement('afterend', div)
    div.setAttribute('class', 'error-message')
    div.innerHTML = '<svg aria-hidden="true" class="icon-error" fill="red" focusable="false" width="20px" height="20px" viewBox="0 0 24 24" xmlns="https://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"></path></svg>'

    p.textContent = 'Use pelo menos 3 caracteres sendo apenas letras minúsculas ou maíusculas'
    p.setAttribute('class', 'name-error')
    div.insertAdjacentElement('beforeend', p)

    div.insertAdjacentElement('beforebegin', icon)
    inputName.style.border = "2px solid red";
    return
  }

  inputName.style.border = "2px solid #008000";
  div.remove()
}

const emailRules = event => {
  const inputValue = event.target.value
  const emailRegex = /[a-z0-9_.]+@[a-z0-9_.]*$/

  if (!emailRegex.test(inputValue)) {
    event.target.insertAdjacentElement('afterend', div)
    div.setAttribute('class', 'error-message')
    div.innerHTML = '<svg aria-hidden="true" class="icon-error" fill="red" focusable="false" width="20px" height="20px" viewBox="0 0 24 24" xmlns="https://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"></path></svg>'

    p.textContent = 'Somente letras (a-z), números (0-9), underlines (_) e pontos (.) são permitidos.'
    p.setAttribute('class', 'name-error')
    div.insertAdjacentElement('beforeend', p)

    div.insertAdjacentElement('beforebegin', icon)
    inputEmail.style.border = "2px solid red";
    return
  }

  inputEmail.style.border = "2px solid #008000";
  div.remove()
}

const passwordRules = event => {
  const inputValue = event.target.value
  const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/

  if (!passwordRegex.test(inputValue)) {
    passwordContainer.insertAdjacentElement('afterend', div)
    div.setAttribute('class', 'error-message')
    div.innerHTML = '<svg aria-hidden="true" class="icon-error" fill="red" focusable="false" width="20px" height="20px" viewBox="0 0 24 24" xmlns="https://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"></path></svg>'

    p.textContent = 'Use oito ou mais caracteres com uma combinação de letras, números e simbolos.'
    p.setAttribute('class', 'name-error')
    div.insertAdjacentElement('beforeend', p)

    div.insertAdjacentElement('beforebegin', icon)
    inputPassword.style.border = "2px solid red";
    return
  }

  inputPassword.style.border = "2px solid #008000";
  div.remove()
}

passwordEye.forEach(eye => {
  eye.addEventListener('click', () => {
    const inputs = eye.previousElementSibling

    if (inputs.type === 'password') {
      inputs.setAttribute('type', 'text')
      eye.innerHTML = '<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M12 7c2.76 0 5 2.24 5 5 0 .65-.13 1.26-.36 1.83l2.92 2.92c1.51-1.26 2.7-2.89 3.43-4.75-1.73-4.39-6-7.5-11-7.5-1.4 0-2.74.25-3.98.7l2.16 2.16C10.74 7.13 11.35 7 12 7zM2 4.27l2.28 2.28.46.46C3.08 8.3 1.78 10.02 1 12c1.73 4.39 6 7.5 11 7.5 1.55 0 3.03-.3 4.38-.84l.42.42L19.73 22 21 20.73 3.27 3 2 4.27zM7.53 9.8l1.55 1.55c-.05.21-.08.43-.08.65 0 1.66 1.34 3 3 3 .22 0 .44-.03.65-.08l1.55 1.55c-.67.33-1.41.53-2.2.53-2.76 0-5-2.24-5-5 0-.79.2-1.53.53-2.2zm4.31-.78l3.15 3.15.02-.16c0-1.66-1.34-3-3-3l-.17.01z"></path></svg>'
      return
    }

    inputs.setAttribute('type', 'password')
    eye.innerHTML ='<svg stroke="currentColor" fill="#202124" stroke-width="0" viewBox="0 0 24 24" height="1rem" width="1rem" xmlns="http://www.w3.org/2000/svg"><path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"></path></svg>'
  })
})

inputName.addEventListener('keyup', nameRules)
inputEmail.addEventListener('keyup', emailRules)
inputPassword.addEventListener('keyup', passwordRules)
```

As dúvidas são:

Por quê quando os dois inputs são preenchidos de forma incorreta, o parágrafo de erro do primeiro input é removido, ou seja, apenas uma mensagem de erro é exibida, e não todos juntos.

Como eu posso validar a confirmação do input "Confirmar" com o input "Password"?

> ![image](https://user-images.githubusercontent.com/70287096/152701883-cfadd0fe-3e44-4cbe-8ec1-4fa89839e81e.png)

@Roger-Melo
