### ISSUE TITLE
sobre a borda do input do formulário

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3022]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/927205

### Descreva a dúvida

```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testUsername = username => /^[a-zA-Z]{6,12}$/.test(username)

form.addEventListener('submit', event => {
  event.preventDefault()

  const isAvalidUsername = testUsername(event.target.username.value)

  if (isAvalidUsername) {
    feedback.textContent = 'Username válido =)'
    return
  }
  feedback.textContent = 'o username deve conter entre 6 a 12 caracteres e apenas letras'
})

form.username.addEventListener('keyup', event => {
  const isAvalidUsername = testUsername(event.target.value)

  if (isAvalidUsername) {
    form.username.setAttribute('class', 'success')
    return
  }
  form.username.setAttribute('class', 'error')
})

```
```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>Validação básica de formulários</title>
</head>

<body>
  <h1>Validação básica de formulários</h1>
  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
    <p class="feedback"></p>
  </form>
  <script src="./app.js"></script>
</body>

</html>
```
```css
body {
  background: #eee;
}

h1 {
  text-align: center;
}

form {
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}

.success {
  border: 2px solid green;
}

.error {
  border: 2px solid red;
}
```
Quando vou digitando o username no input a borda não muda a cor, só quando digito tudo e clico fora que muda. 
```js
form.username.addEventListener('keyup', event => {
  const isAvalidUsername = testUsername(event.target.value)

  if (isAvalidUsername) {
    form.username.setAttribute('class', 'success')
    return
  }
  form.username.setAttribute('class', 'error')
})

```
Porém, quando o código está assim: 
 ```js
form.username.addEventListener('keyup', event => {
const isAvalidUsername = testUsername(event.target.value)

  if (isAvalidUsername) {
    console.log('username válido')
    return
  }
  console.log('username inválido')
})
```
Vai aparecendo no console se é válido ou inválido. Por que isso está acontecendo?
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

> ## Quando vou digitando o username no input a borda não muda a cor, só quando digito tudo e clico fora que muda

Esse mesmo problema foi relatado em uma [issue que o Rodrigo abriu](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1932).

Acredito que nessa issue vc encontrará a resposta.

Caso reste alguma dúvida, pode comentar aqui nessa issue que te ajudo =)

**Comment by Jansen-Muniz** [comment]
vou dar uma olhada aqui mestre =)

**Comment by Jansen-Muniz** [comment]
Roger, eu acrescentei `outline: none;` aqui e deu certo.

```css
input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
  outline: none;
}
```
