### ISSUE TITLE
Resumo da Aula 02-02 da etapa 10 - construindo um relógio digital

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3359]
```js
const clockContainer = document.querySelector('.clock-container')

const updateClock = () => {
  const present = new Date()
  const hours = present.getHours()
  const minutes = present.getMinutes()
  const seconds = present.getSeconds()

  clockContainer.innerHTML = `
    <span>${String(hours).length === 1 ? `0${hours}` : hours}</span> :
    <span>${String(minutes).length === 1 ? `0${minutes}` : minutes}</span> :
    <span>${String(seconds).length === 1 ? `0${seconds}` : seconds}</span>
  `
}

setInterval(updateClock, 1000)
```
```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css">
  <title>Construindo um relógio digital</title>
</head>

<body>
  <div class="clock-container"></div>
  <script src="./app.js"></script>
</body>

</html>
```
```css
body {
  background-color: #212121;
}

.clock-container {
  font-size: 4em;
  text-align: center;
  margin: 200px auto 0;
  color: #FFF;
  font-family: Arial, Helvetica, sans-serif;
}

.clock-container span {
  padding: 20px;
  background: #006ce6;
  border-radius: 10px;
}
```
