### ISSUE TITLE
If else nao esta pegando o valor indicado

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#3995]
### Etapa da aula

7

### Nome da aula

Template HTML e checando as respostas - Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/943417

### Descreva a dúvida

Não consigo fazer com que quando a opção selecionda for B e A, a opção A receba a classe 'errado', ela esta recebendo a classe certo , já fiz de tudo, e nada.
A Resposta correta é sempre opcao B.
Em JS o erro especifico esta comentado como //ERRO TENHO QUE VERIFICAR ****

```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <h1>Rodolfo Rondinely da Silva</h1>

   <!--  <div>
        <p>Hell World</p>
        <p>Oi</p>
        <p class="error">Essa  é uma mensagem de erro</p>
    </div>
    <div class="error"> Outra mensagem de erro</div>
    <h1 id="title"> Paragrafo de erro com id</h1>

    <h1 class="active list-group-item">LISTA DE AFAZERES</h1>

    <ul class="active list-group-item p-3 mb-2 bg-secondary text-white border border-light ">
        <span><li class="d-flex justify-content-between">FAZER PARA CASA <span>x</span></li></span>
        <span>  <li class="d-flex justify-content-between">LAVAR A LOUÇA <span>x</span></li></span>
        <span> <li class="d-flex justify-content-between">LIMPAR A CASA <input type="checkbox" name="lione" id=""></li></span>
        <span>  <li class="d-flex justify-content-between">ESTUDAR <input type="checkbox" name="lione" id=""> </li></span>
        <span>  <li class="d-flex justify-content-between">DORMI BEM <input type="checkbox" name="lione" id=""> </li></span>
    </ul> -->

            <!-- QUIZ COM JS -->

 <div class="p-3 mb-2 bg-primary text-white">
    <h2>QUIZ</h2>
</div>
<form class="form">
    <div class="card" style="width:50rem;">
        <div class="card-body">
            <h5 class="card-title">Qual numero é maior ?</h5>
                 <div class="perguntas">
                   <input class="form-check-input card-title" type="radio" name="escolha1" id="escolha1"value="A">
                    <label class="form-check-label" for="escolha1">
                        Numero 3
                    </label>
                </div>
                <div class="perguntas">

                <input class="form-check-input card-title" type="radio" name="escolha1"  id="escolha2" value="B">
                    <label class="form-check-label" for="escolha2">
                        Numero 8
                    </label>
                </div>
                    <div class="res1"></div>
         </div>

    </div>

    <div class="card" style="width:50rem;">
        <div class="card-body">
            <h5 class="card-title">Qual é o numero par?</h5>
            <div class="perguntas">
                <input class="form-check-input card-title" type="radio" name="escolha2" id="escolha3" value="A">
                    <label class="form-check-label" for="escolha3">
                        Numero 3
                    </label>
                </div>

            <div class="perguntas">

                <input class="form-check-input card-title" type="radio" name="escolha2" id="escolha4" value="B">
                    <label class="form-check-label" for="escolha4">
                        Numero 8
                    </label>
                </div>
                <input type="submit" class="btn btn-primary" value="Confirmar">

        </div>
        <div class="res2"></div>

    </div>
    
</form>
  <div class="res card">...</div>



   <script src="js.js"></script>
   <script src="quiz.js"></script>
</body>
</html>
```

```css
body{
    background: #cccaaa;
}
.active{
    width: 400px;
}
.d-flex:hover{
    background-color: aquamarine;
    color: blueviolet;
    font-weight: bolder;
    
}
.tacahado{
    text-decoration: line-through;
    background-color: white;
    color: red;
    font-weight: bold;
}
.text-white{
    display: flex;
    justify-content: center;
}
.res{
    margin: 5px;
    margin-left: -2px;
    padding: 10px;
    width: 50rem;
}
.res span{
    color: red;
    font-weight: bold;
}
.res .error {
    color:red;
    font-weight: bolder;    
    text-shadow: 2px 1px 12px black ;

}
.certo{
    background-color: rgb(159, 230, 93);
    box-sizing: border-box;
    width: 95%;
    height: 50px;
    display: flex;
    align-items: center;

    border-radius: 5px;
    color: brown;
    font-weight: bolder;
    text-shadow: 2px 2px 2px whitesmoke;
    text-transform: uppercase;
}
.errado{
    background-color: rgb(224, 30, 24);
    box-sizing: border-box;
    width: 95%;
    height: 50px;
    display: flex;
    align-items: center;
    border-radius: 5px;

    color: rgb(217, 243, 200);
    font-weight: bolder;
    text-shadow: 2px 5px 12px rgb(92, 30, 30);
    text-transform: uppercase;
}
```

```js
/* CRIAR UM ARRAY COM AS RESPOSTAS CERTAS */
const gabarito=['B','B']

const form = document.querySelector('.form')
const res = document.querySelector('.res')
let certo = document.querySelector('.certo')
const res1 = document.querySelector('.res1')    //modal da resposta pergunta1
const res2 = document.querySelector('.res2')    //modal da resposta pergunta2

const escolhaA = form.escolha1      //pegando do form o que foi selecioando
const escolhaB = form.escolha2
const A = escolhaA                  //armazendo o que foi selecioando
const B = escolhaB 

form.addEventListener('submit', event=>{
    event.preventDefault()
    if (A.value=='A' & B.value=='A') {
        res1.innerHTML = `
        <div class="errado">Número 3 é menor do que 8, lembra ele vem antes do OITO ?<br>
       Mas valeu pelo esfoço, você vai longe !!! </div>
`   
        res2.innerHTML= `<div class="errado">
         Numero 3 é IMPAR, Lembre-se numeros terminados com 1,3,5,7 são impares e numeros terminados com 0,2,4,6,8, são Pares
         </div>`
        }
        else if
    (A.value=='A' & B.value=='B'){
        res1.innerHTML =`
         <div class="errado">Número 3 é menor do que 8, lembra ele vem antes do OITO </div>
        ` 
        res2.innerHTML = 
        `
         <div class="certo">
        Número 8 é par, Parabéns !!! Numeros pares são terminados em 0,2,4,6,8 
        `
    }
        else if
    (A.value=='B' & B.value=='A'){    //ERRO TENHO QUE VERIFICAR ****
        res1.innerHTML =`
        <div class="certo">Parabéns !!! 8 é maior que 3 </div>
        `
        res2.innerHTML= `
        <div class="errado">
        Número 3 é ímpar, e número 8 é par !!! Você se lembra ?</div>
        `
      
    }else if
    (A.value=='B' & B.value=='B'){
        res1.innerHTML =`
        <div class="certo">Parabéns !!! 8 é maior que 3</div>
`
        res2.innerHTML = `
        <div class="certo">Parabéns !!! 8 é par , você acertou tudo !</div>
        `
    }
    else{
        res.innerHTML = `<span>Por favor, verifique as respostas, pois há questões sem respostas<span>`
    }
  
})


  
  /*   if((gabarito[0] & A.value =='B') & ( gabarito[1] & A.value =='B'))   {

    alert('WEWEW')
        //res.innerHTML = `Voce errou a PERGUNTA 1 e 2, vamos estudar um pouco mais !`
    } */
    /* else if((gabarito[0] & A.value =='A' ) & ( gabarito[1] & B.value =='B')){
        res.innerHTML = `Voce errou a PERGUNTA 1 e ACERTOU  a pergunta 2, vamos estudar um pouco mais, estamos 50% !`
    }
    else if((gabarito[0] & A.value =='B') & (gabarito[1] & B.value=='A')){
        res.innerHTML = `Voce ACERTOU a pergunta 1 e errou a pergunta 2, vamos estudar um pouco mais, estamos 50% !`
    }
    else if( (gabarito[0] & A.value =='B') & ( gabarito[1] & B.value=='B')){
        res.innerHTML = `Voce ACERTOU  a pergunta 1 E 2, PARABENS VOCE ESTA 100% !`
    }
    */

```

@Roger-Melo
