### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 - da etapa 05

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#4104]
# Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 - Resumo

## O que faz o método .classList.add( )?
Esse método adiciona uma classe a um elemento HTML.

## O que faz o método .classList.remove( )?
Esse método remove uma classe de um elemento HTML.

```html
<!-- Vou criar um título h1 sem classe -->

<h1>Título</h1>
```

```css
/*
Classes que serão inseridas ou removidas do elemento HTML
*/

.error {
  padding: 1rem;
  color: crimson;
  border: 1px solid crimson;
}

.success {
  padding: 1rem;
  color: green;
  border: 1px solid green;
}
```

```javascript
/*
Vou declarar uma variável para usar esse título no DOM
*/

const title = document.querySelector('h1')

/*
Vou inserir a classe error
*/

title.classList.add('error')

/*Vou remover a classe error */

title.classList.remove('error')
```

## O que faz o método .classList.toggle( )?
Esse método remove e adiciona uma classe a um elemento HTML.

```javascript
/*
Vou declarar uma variável para usar esse título no DOM
*/

const title = document.querySelector('h1')

/*
Vou inserir a classe success
*/

title.classList.add('success')

/*Vou remover a classe success */

title.classList.toggle('success')

/*Vou inserir de novo a classe success */

title.classList.toggle('success')
```
