### ISSUE TITLE
Desenvolvendo um popup - Aula 04-04 da etapa 05

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4597]
![js](https://user-images.githubusercontent.com/55354801/183546272-ddb858cc-4147-423b-80ad-1c2b12fcf009.jpg)

# Desenvolvendo um popup - Aula 04-04 da etapa 05

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Desenvolvendo um Popup</title>
  <link rel="stylesheet" href="./style.css">
</head>
<body>
  <button>Clique aqui</button>

  <div class="popup-wrapper">
    <div class="popup">
      <div class="popup-close">x</div>

      <div class="popup-content">
        <h2>Popup deselegante</h2>
        <p>O autor do popup foi o programador Ethan Zuckerman.</p>
        <a class="popup-link" href="#">Saiba mais</a>
      </div>
    </div>
  </div>

  <script src="./app.js"></script>
</body>
</html>
```

```css
* {
  box-sizing: border-box;
}

button {
  display: block;
  margin: 20px auto;
  background: crimson;
  color: white;
  border: 0;
  cursor: pointer;
  padding: 6px 10px;
}

.popup-wrapper {
  display: none;
  background: rgba(0, 0, 0, .5);
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.popup {
  font-family: arial;
  text-align: center;
  width: 100%;
  max-width: 300px;
  margin: 10% auto;
  padding: 20px;
  background: white;
  position: relative;
}

.popup a {
  color: white;
  cursor: pointer;
  padding: 6px 10px;
  text-decoration: none;
  background: crimson;
}

.popup-close {
  position: absolute;
  top: 5px;
  right: 10px;
  cursor: pointer;
}
```

```jsx
const button = document.querySelector('button');
const popup = document.querySelector('.popup-wrapper');
//const closeButton =  document.querySelector('.popup-close');

button.addEventListener('click', () => {
  popup.style.display = 'block';
})

/*closeButton.addEventListener('click', () => {
  popup.style.display = 'none';
});*/

popup.addEventListener('click', event => {
  const classNameOfClickedElement = event.target.classList[0]
  const classNames = ['popup-close', 'popup-wrapper', 'popup-link']
  const shouldClosePopup = classNames.some(className => className === classNameOfClickedElement)
	// some() ve se tem algum daqueles itens do array , não é necessário fazer aquele if enorme e retornando true ele da um dispay none.
  if (shouldClosePopup) {
    popup.style.display = 'none';
  }
})
```

O método **`some()`** testa se ao menos um dos elementos no array passa no teste implementado pela função atribuída e retorna um valor **`true`** ou **`false`**.

Qual é a diferença entre some e find?

A diferença está na saída. **find retornará o valor, alguns retornarão um boolean** .
