### ISSUE TITLE
O evento submit - Aula 01-03 da etapa 06

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4599]
![js](https://user-images.githubusercontent.com/55354801/183546693-20750e4f-a9af-458d-a4d4-bf6c34e04609.jpg)
# O evento submit - Aula 01-03 da etapa 06

O evento **onSubmit** do JavaScript é uma ótima forma de se automatizar tarefas. Com ele, você pode fazer o navegador validar as informações que foram enviadas através de um formulário antes que o servidor as receba

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>O evento submit</title>
  <link rel="stylesheet" href="./style.css">
</head>
<body>
  <h1>O evento submit</h1>

  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
  </form>

  <script src="./app.js"></script>
</body>
</html>
```

```css
body {
  background: #eee;
}

h1 {
  text-align: center;
}

form {
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}
```

```jsx
const form = document.querySelector('.signup-form');
// const usernameInput = document.querySelector('#username)

form.addEventListener('submit', event => {
  event.preventDefault() // previne o valor default de ficar carregando a pagina
  
  console.log(event.target.username.value) // valor digitado no campo input
})
```
