### ISSUE TITLE
Eventos do teclado - Aula 02-03 da etapa 06

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4603]
![js](https://user-images.githubusercontent.com/55354801/183547213-169bdf3c-0820-4019-9464-adf06ef01179.jpg)

# Eventos do teclado - Aula 02-03 da etapa 06

[https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>O evento submit</title>
  <link rel="stylesheet" href="./style.css">
</head>
<body>
  <h1>O evento submit</h1>

  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
    <p class="feedback"></p>
  </form>

  <script src="./app.js"></script>
</body>
</html>
```

```css
body {
  background: #eee;
}

h1 {
  text-align: center;
}

form {
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}

.success {
  border: 2px solid green;
}

.error {

  border: 2px solid red;
}
```

```jsx
const form = document.querySelector('.signup-form');
const feedback = document.querySelector('.feedback');

const testUsername = username => /^[a-zA-Z]{6,12}$/.test(username)

form.addEventListener('submit', event => {
  event.preventDefault()

  if (isAValidUserName) {
    feedback.textContent = 'username válido =)'
    feedback.style.color = 'green'
    return
  }

  feedback.textContent = 'o username deve conter entre 6 a 12 caracteres e deve conter apenas letras.'
  feedback.style.color = 'red'
})

form.username.addEventListener('keyup', event => {
  const isAValidUserName = testUsername(event.target.value)

  if (isAValidUserName) {
    form.username.setAttribute('class', 'success')
    return
  }

  form.username.setAttribute('class', 'error')
})
```
