### ISSUE TITLE
Resumo da Aula Construindo um relógio digital - Aula 02-02 - da etapa 10

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#4906]
# Construindo um relógio digital - Aula 02-02 - Resumo

```html
<div class="clock-container"></div>
```

```css
body {
  background-color: #212121;
}

.clock-container {
  font-size: 4rem;
  text-align: center;
  margin: 12.5rem auto 0;
  color: #ffffff;
  font-family: Arial;
}

.clock-container span {
  padding: 1.5rem;
  background: #006CE6;
  border-radius: 10px;
}
```

```jsx
// Obter e armazenar a referência da div
const clockContainer = document.querySelector(".clock-container")

/*
Implementar uma função para atualizar as horas do reológio a 
cada segundo
*/

const updateClock = () => {

// Objeto de data que representa o momento atual
const present = new Date();
// Constante para mostrar as horas
const hours = present.getHours()
// Constante para mostrar os minutos
const minutes = present.getMinutes()
// Constante para mostrar os segundos
const seconds = present.getSeconds()

// Exibir o relógio na tela
clockContainer.innerHTML = `
 <span>${String(hours).length === 1 ? `0${hours}` : hours}</span> :
  <span>${String(minutes).length === 1 ? `0${minutes}` : minutes}</span> :
  <span>${String(seconds).length === 1 ? `0${seconds}` : seconds}</span>
`

}

// Usar o método setInterval para executar a função a cada 1 segundo
setInterval(updateClock, 1000)
```
