### ISSUE TITLE
Duvida na aula sobre Eventos do teclado

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5336]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/927205

### Descreva a dúvida

Olá! Na aula de eventos de teclado, estou seguindo o código apresentado mas o resultado está diferente,  não consigo fazer com que no momento em que aperto uma ou mais teclas o input fique automaticamente da cor vermelha ou verde.
Ao invés disso o resultado está sendo que ao digitar alguma tecla o input permanece inalterado, e somente quando aperto tab ou clico na área em volta é que a cor do input muda para vermelho ou verde. Já reescrevi o código algumas vezes e o resultado permanece o mesmo, vou deixar aqui para vocês darem uma olhada.

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="./styleCSS.css">
        <title>Aula Etapa 6</title>
</head>
<body>
    <h1>Validação de Formulários</h1>

    <form class="signup-form">
        <input type="text"  id="username" placeholder="username" autofocus>
        <button>Enviar</button>
        <p class="feedback"></p>
    </form>

    <script src="./appAula.js"></script>
</body>
</html>
```
------------------------

```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testUserName = username => /^[a-zA-Z]{6,12}$/.test(username)


form.addEventListener('submit', (event) => {
  event.preventDefault()

  const isAValidUserName = testUserName(event.target.username.value)

  if(isAValidUserName) {
    feedback.textContent = 'validacao certa'
    return
  }
  feedback.textContent = 'validacao errada'
})

form.username.addEventListener('keyup', (event) => {
              const isAValidUserName = testUserName(event.target.value)
              
            
              if(isAValidUserName) {
               form.username.setAttribute('class', 'sucess')
                return
              }
              form.username.setAttribute('class', 'erro')
})
```
---------------------------------------

```css
body {
    background: #eee;
}

h1 {
    text-align: center;
}

form {
    max-width: 200px;
    margin: 40px auto;
    background: white;
    padding: 10px;
}

input, button {
    display: block;
    margin: 10px auto;
    padding: 4px;
}

.sucess {
    border: 2px solid green;
}

.erro {
    border: 2px solid red;
}
```

@Roger-Melo
