### ISSUE TITLE
Dúvida sobre a mudança de style no input(text) do form.

### ISSUE THREAD

**Issue by LWagg** [roger-melo-treinamentos/curso-de-js-roger-melo#5377]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/927205

### Descreva a dúvida

    Olá, na aula me pareceu que a cada letra digitada pelo professor, a cor se mantinha vermelha até dar match com o Regex. Mesmo acompanhando a aula, percebi que a cor (vermelha ou verde) só aparece quando eu clico fora da caixa do input. Olhei o código algumas vezes e não descobri o que pode ser.

```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')


const testUsername = username => /^[a-zA-z]{6,12}$/.test(username)


form.addEventListener('submit', event => {
    event.preventDefault() 

    const isAValidUsername = testUsername(event.target.username.value)
    
    if (isAValidUsername) {
        feedback.textContent = 'Username válido!'
        return
    }

    feedback.textContent = 'O username deve conter entre 6 a 12 caracteres e deve conter apenas letras'
    
})

form.username.addEventListener('keyup', event => {
    const isAValidUsername = testUsername(event.target.value)

    if (isAValidUsername) {
        form.username.setAttribute('class', 'success')
        return
    }

    form.username.setAttribute('class', 'error')
})
```

```HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Eventos do teclado</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Eventos do teclado</h1>
    
    <form class="signup-form">
        <input type="text" id="username" placeholder="username" autofocus>
        <button>Enviar</button>
        <p class="feedback"></p>
    </form>

    <script src="app.js"></script>
</body>
</html>
```
```CSS
body {
    background: #eee;
}

h1 {
    text-align: center;
}

form {
    max-width: 200px;
    margin: 40px auto;
    background: white;
    padding: 10px;
}

input, button {
    display: block;
    margin: 10px auto;
    padding: 4px;
}

.success {
    border: 2px solid green;
}

.error {
    border: 2px solid red;
}
```

@Roger-Melo
