### ISSUE TITLE
Resumo da Aula 02-02 da etapa 10

### ISSUE THREAD

**Issue by acdona** [roger-melo-treinamentos/curso-de-js-roger-melo#5545]
# Aula 02-02 da etapa 10
## HTML
```HTML
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./favicon.ico">
    <link rel="stylesheet" href="./style.css">
    <title>Aula 02-02 etapa 10</title>
</head>
<body>
    <h1>Construindo um relógio digital</h1>
    <div class="clock-container">

        <!-- Digital clock -->
        <div id="time">
            <div id="hours" style="--clr:#ff2972;">00</div>
            <div id="minutes" style="--clr:#fee800;">00</div>
            <div id="seconds" style="--clr:#04fc43;">00</div>
            <div id="ampm">AM</div> 
        </div>
    </div>
<script src="./app.js"></script>
</body>
</html>
```
#
## CSS
```CSS
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,600;0,700;0,800;0,900;1,300;1,500&display=swap');

* {
    margin: 0;
    padding: 0;

    box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;

    font-family: 'Poppins', sans-serif;
}

body {
    display: flex;
    min-height: 100vh;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    background-color: #2f363e;
}

.container {
    position: relative;
    background: #2f363e;
    /* min-height: 500px; */
    border-radius: 20px;
    border-top-left-radius: 225px;
    border-top-right-radius: 225px;
    box-shadow: 25px 25px 75px rgba(0, 0, 0, 0.75),
        10px 10px 70px rgba(0, 0, 0, 0.25),
        inset 5px 5px 10px rgba(0, 0, 0, 0.5),
        inset 5px 5px 20px rgba(255, 255, 255, 0.2),
        inset -5px -5px 15px rgba(0, 0, 0, 0.75);
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}

/* digital clock style */

#time {
    margin-bottom: 40px;
    display: flex;
    padding: 10px 20px;
    font-size: 2em;
    font-weight: 600;
    border: 2px solid rgba(0, 0, 0, 0.5);
    border-radius: 40px;
    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5),
        inset 5px 5px 20px rgba(255, 255, 255, 0.2),
        inset -5px -5px 15px rgba(0, 0, 0, 0.75)
}

#time div {
    position: relative;
    width: 60px;
    text-align: center;
    font-weight: 500;
    color: var(--clr);
}

#time div:nth-child(1)::after,
#time div:nth-child(2)::after {
    content: ':';
    position: absolute;
    right: -4px;
}

#time div:last-child {
    font-size: 0.5em;
    display:flex;
    justify-content: center;
    align-items: center;
    color: #fff;  
}

#time div:nth-child(2)::after {
    animation: animate 1s steps(1) infinite;
}

@keyframes animate {
    0% {
        opacity: 1;
    }
    50% {
        opacity: 0;
    }
}
```
#
## JAVASCRIPT

```js
const updateClock = () => {
    const hours = document.querySelector('#hours')
    const minutes = document.querySelector('#minutes')
    const seconds = document.querySelector('#seconds')
    const ampm = document.querySelector('#ampm')
    const present = new Date()
    let hour = present.getHours()
    let minute = present.getMinutes()
    let second = present.getSeconds()
    let am = hour >= 12 ? "PM" : "AM";

    // add zero before single digit number
    hour = (hour < 10) ? `0${hour}` : hour
    minute = (minute < 10) ? `0${minute}` : minute
    second = (second < 10) ? `0${second}` : second

    hours.innerHTML = hour
    minutes.innerHTML = minute
    seconds.innerHTML = second
    ampm.innerHTML = am
}

setInterval(updateClock, 1000)
```
