### ISSUE TITLE
Resumo da Aula Desenvolvendo um popup - Aula 04-04 da etapa 05

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#6145]
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <title>POPUP</title>
</head>
<body>
    <button>Clique aqui</button>
   
    <div class="popup-wrapper">
        <div class="popup">
            <div class="popup-close">x</div>
            <div class="popup-content">
                <h2>Popup deselegante</h2>
                <p>O autor do pop foi o programador Luna</p>
                <a class="popup-link" href="#">Saiba mais</a>
            </div>
        </div>
    </div>
    <script src="app.js"></script>
</body>
</html>
```

```js
const popupWrapper = document.querySelector('.popup-wrapper')
const buttonPopup = document.querySelector('button')

buttonPopup.addEventListener('click', () => {
    popupWrapper.style.display =  'block'
})


popupWrapper.addEventListener('click', event => {
    const classNameOfClickedElement = event.target.classList[0]
    const classNames = ['popup-close', 'popup-link',  'popup-wrapper']
    const shouldClosePopup = classNames.some(className => className === classNameOfClickedElement)  
    /*
        O método some() testa se ao menos um dos elementos no array passa no teste 
        implementado pela função atribuída e retorna um valor true ou false.
    */
    if(shouldClosePopup){
           popupWrapper.style.display =  'none'
       }
})
```

```css
*{
    box-sizing: border-box;
}

button {
    display: block;
    margin: 20px auto;
    background-color: crimson;
    color: white;
    border: 0;
    cursor: pointer;
    padding: 6px 10px
}

.popup-wrapper{
    display: none;
    background-color: rgba(0, 0, 0, 0.5);
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.popup{
    font-family: arial;
    text-align: center;
    width: 100%;
    max-width: 300px;
    margin: 10% auto;
    padding: 20px;
    background: white;
    position: relative;
}

.popup a{
    color: white;
    border: 0;
    cursor: pointer;
    padding: 6px 10px;
    text-decoration: none;
    background: crimson;
}

.popup-close {
    position: absolute;
    top: 5px;
    right: 10px;
    cursor: pointer;
}
```
