### ISSUE TITLE
Resumo da Aula - 01-03 O evento submit  da etapa 06

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#6227]
```html
<body>
   
    <h1>o evento submit</h1>
  
    <form class="signup-form">
        <input type="text" id="username" name="user" placeholder="username" autofocus>
        <button>Enviar</button>
    </form>
</body>
```
```css
body{
    background: #eee;
    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
}

h1{
    text-align: center;
}

form {
    max-width: 200px;
    margin: 40px auto;
    background: #fff;
    padding: 10px;
}

input, button {
    display: block;
    margin: 10px auto;
    padding: 4px;
}
```

```js
const form = document.querySelector('.signup-form')
const inputUserName = document.querySelector('#username')

form.addEventListener('submit', event => {
    //previne que a página seja recarregada após o envio do form 
    event.preventDefault() 

    console.log(inputUserName.value);

    //quando o input dentro do form tem um ID 
    //o valor do input pode ser acessado como abaixo
    console.log(form.username.value);

    //quando o input dentro do form tem o atributo name 
    //o valor do input pode ser acessado como abaixo
    console.log(form.user.value);
})
```
