### ISSUE TITLE
Resumo da Aula Desenvolvendo um popup - Aula 04-04 da etapa 05

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6376]
# Desenvolvendo um popup

Agora vamos desenvolver um `popup`.

o arquivo HTML:
```html
<head>
    <meta charset="UTF-8">
    <title>Desenvolvendo um popup</title>

    <link rel="stylesheet" href="style.css">

</head>

<body>
    <button>Clique aqui</button>

    <div class="popup-wrapper">
        <div class="popup">
            <div class="popup-close">x</div>

            <div class="popup-content">
                <h2>Popup deselegante</h2>
                <p>O autor do popup foi o programador Ethan Zuckerman</p>
                <a class="popup-link" href="#">Saiba mais</a>
            </div>
        </div>
    </div>
    
    <script src="app.js"></script>
</body>
```
o nosso arquivo CSS:
```css
* {
    box-sizing: border-box;
}

button {
    display: block;
    margin: 20px auto;
    background: crimson;
    color: white;
    border: 0;
    cursor: pointer;
    padding: 6px 10px;
}

.popup-wrapper {
    display: none;
    background-color: rgba(0, 0, 0, 0.5);
    position: fixed;
    top:0;
    left: 0;
    width: 100%;
    height: 100%;
}

.popup {
    font-family: Arial, Helvetica, sans-serif;
    text-align: center;
    width: 100%;
    max-width: 300px;
    margin: 10% auto;
    padding: 20px;
    background-color: white;
    position: relative;
}

.popup a {
    color: white;
    border: 0;
    cursor: pointer;
    padding: 6px 10px;
    text-decoration: none;
    background: crimson;
}

.popup-close {
    position: absolute;
    top: 5px;
    right: 10px;
    cursor: pointer;
}
```
  ## Mostrando o popup

No arquivo CSS colocamos a classe `popup-wrapper` com display `none`, agora vamos adicionar no botão para quando for clicado mudar o display da classe.

Buscamos as referencias no DOM:
```js
const button = document.querySelector('button')
const popup = document.querySelector('.popup-wrapper')
```

Adicionamos um `eventListener` no button que mudar o display para `block`:
```js
button.addEventListener('click', () => {
    popup.style.display = `block`
})
```

## Fechando o popup

Para fecharmos o popup, adicionamos um evento que quando clicado muda o display para `none`:
```js
popup.addEventListener('click', event => {
    popup.style.display = `none` 
})
```
> Mas dessa maneira o popup fechará quando clicarmos em qualquer elemento do `popup-wrapper`.

Mas vamos fechar esse popup de uma maneira diferente.

vamos limitar o fechamento do popup para quando as classes `popup-close`, `popup-wrapper`, `popup-link`.

Colocamos as classes que devem fechar o popup em um array.
```js
popup.addEventListener('click', event => {
    const className = ['popup-close', 'popup-wrapper', 'popup-link']
})
```

Agora pegamos o alvo do clique e guardamos sua classe em uma variável:
```js
popup.addEventListener('click', event => {
    const className = ['popup-close', 'popup-wrapper', 'popup-link']

    const { target } = event
    const classNameOfClickedElement = target.classList[0]

})
```

Agora com o método `.some` verificamos se a classe do alvo encontrasse na nossa lista de classes que fecham o popup.

> O método `.some` percorre o array e se a expressão der `true` ele quebra o loop e retorna `true`, mas se ele não encontrar retorna `false`.

```js
popup.addEventListener('click', event => {
    const { target } = event
    const classNameOfClickedElement = target.classList[0]

    const className = ['popup-close', 'popup-wrapper', 'popup-link']

    shouldClosePopup = className.some(className => 
        className === classNameOfClickedElement)
    
    if (shouldClosePopup) {
        popup.style.display = `none` 
    }
})
```
