### ISSUE TITLE
Resumo da Aula Construindo um Relógio Digital - Aula 02-02 da etapa 10

### ISSUE THREAD

**Issue by dev-pedro** [roger-melo-treinamentos/curso-de-js-roger-melo#6461]
# Construindo um Relógio Digital - Aula 02-02

#### Código que utilizei nesta aula

HTML:

```html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./style.css" />
    <title>Construindo um relógio digital</title>
  </head>

  <body>
    <div class="full-date"></div>
    <div class="clock-container"></div>

    <script src="./app.js"></script>
  </body>
</html>
```

CSS:

```css
* {
  margin: 0;
  padding: 0;
}

body {
  background: radial-gradient(gray, black);
  /* background: gray; */
  height: 100vh;
  width: 100vw;
}

.full-date {
  font-size: 30px;
  color: rgb(255, 238, 0);
  width: 100%;
  height: 50px;
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin-bottom: 10px;
  margin-top: 0;
}

.clock-container {
  display: flex;
  width: 100%;
  justify-content: center;
  align-items: center;
}

.hours {
  font-size: 85px;
  color: #fff;
  padding: 8px;
  background: red;
  border-radius: 10px;
}

.minutes {
  font-size: 65px;
  color: white;
  padding: 8px;
  background: green;
  border-radius: 10px;
}

.seconds {
  font-size: 45px;
  color: white;
  padding: 8px;
  background: #799dff;
  border-radius: 10px;
}

.ampm {
  padding: 5px;
  display: flex;
  align-self: self-start;
  font-size: 30px;
  color: #c0c0c0;
}

span[data-dot] {
  padding: 5px;
  color: #c0c0c0;
  font-size: 50px;
}
```

Javascript:

```javascript
const clockContainer = document.querySelector('.clock-container')
const fullDateContainer = document.querySelector('.full-date')

const updateClock = () => {

  const options = {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  }
  const present = new Date()
  const datePresentFormated = new Intl.DateTimeFormat('pt-BR', options).format(
    present
  )
  const hours = present.getHours()
  const ampm = hours < 12 ? 'AM' : 'PM'
  const minutes = present.getMinutes()
  const seconds = present.getSeconds()

  const fullDateHTML = `
    <span>${datePresentFormated}</span>
  `
  const clockHTML = `
        <span class="hours">${
          String(hours).length === 1 ? `0${hours}` : hours
        }</span> <span data-dot>:</span>
        <span class="minutes">${
          String(minutes).length === 1 ? `0${minutes}` : minutes
        }</span> <span data-dot>:</span>
        <span class="seconds">${
          String(seconds).length === 1 ? `0${seconds}` : seconds
        }</span>
        <span class="ampm">${ampm}</span>

    `
  fullDateContainer.innerHTML = fullDateHTML
  clockContainer.innerHTML = clockHTML
}

setInterval(updateClock, 1000)
```

##### Objeto construtor `Intl.DateTimeFormat` em javascript

O objeto construtor `Intl.DateTimeFormat` em JavaScript é usado para formatar datas e horas de acordo com as convenções culturais e de localidade do usuário. Ele permite que você especifique o idioma, o país e as opções de formatação para exibir datas e horas em diferentes formatos.

Aqui está um exemplo básico de como usar o `Intl.DateTimeFormat` para formatar uma data em um determinado idioma:

```javascript
const date = new Date();
const options = { 
  weekday: 'long', 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
};
const formatter = new Intl.DateTimeFormat('pt-BR', options);
console.log(formatter.format(date)); // Output: "quarta-feira, 4 de abril de 2023"
```

Nesse exemplo, o construtor `Intl.DateTimeFormat` cria um objeto de formatação que formata a data em português do Brasil com o formato "quarta-feira, 4 de abril de 2023".

Além disso, você também pode passar outras opções de formatação, como `hour`, `minute`, `second`, `hour12` (para usar um relógio de 12 horas), `timeZoneName` (para exibir o nome da zona de tempo) e muito mais.

Em resumo, o `Intl.DateTimeFormat` é uma maneira útil de formatar datas e horas em diferentes idiomas e formatos, o que é especialmente útil para aplicativos da web que precisam exibir datas e horas em diferentes localidades.

Para mais informações acesse o link abaixo:

[Intl.DateTimeFormat - JavaScript | MDN](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)
