### ISSUE TITLE
Duvida resolução do exercicio

### ISSUE THREAD

**Issue by matheusmoraesn** [roger-melo-treinamentos/curso-de-js-roger-melo#6692]
### Etapa da aula

7

### Nome da aula

Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706739

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

 Ao tentar com que apareça a mensagem de erro após clicar no botão, só aparece a mensagem de sucesso.
não sei se é falta de atenção, mas não encontro o erro, gostaria de um auxilio

```js
const input = document.querySelector('#username')
const p = document.createElement('p')
const form = document.querySelector('form')
const regex = /^[a-zA-Z]{6,}$/
const button = document.querySelector('button')
input.addEventListener('keyup', event => {
  event.preventDefault()
  const valor = regex.test(event.target.value)
  console.log(valor)

  if(valor) {
    p.textContent=('Username válido =)')
    p.setAttribute('class','username-success-feedback')
    event.target.insertAdjacentElement('afterend',p)
    return
  }
  p.textContent=('O valor deve conter no mínimo 6 caracteres,com apenas letras maiúsculas e/ou minúsculas')
  p.setAttribute('class','username-help-feedback')
  event.target.insertAdjacentElement('afterend', p)

})


form.addEventListener('submit', event=>{
  event.preventDefault()  
  const valor = event.target.value
  if(!regex.test(valor)){
    console.log(!regex.test(event.target.value))
    p.textContent=('Por favor insira um username valido')
    p.setAttribute('class','submit-help-feedback')
    button.insertAdjacentElement('afterend',p)
    
  } else {
  p.textContent=('dados enviados =)')
  p.setAttribute('class','submit-success-feedback')
  button.insertAdjacentElement('afterend',p)
}})

```

```HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">

  <link rel="stylesheet" href="./style.css">
  <title>Exercício 18</title>
</head>
<body>
  <div class="container">
    <h1>Exercício 18</h1>

    <form>
      <fieldset>
        <label for="username">Nome de usuário</label>
        <input
          type="text"
          placeholder="Cadastre seu nome de usuário"
          id="username"
          autofocus
        >

        <button class="button">Enviar</button>
      </fieldset>
    </form>
  </div>

  <script src="./app.js"></script>
</body>
</html>

```

```CSS
.container {
  max-width: 80rem;
  padding-top: 7.5rem;
}

.username-help-feedback {
  margin-bottom: 2.5rem;
  color: darkorange;
}

.username-success-feedback {
  margin-bottom: 2.5rem;
  color: green;
  font-weight: bold;
}

.submit-help-feedback {
  margin-bottom: 2.5rem;
  color: red;
}

.submit-success-feedback {
  margin-bottom: 2.5rem;
  background-color: green;
  color: black;
}

```

@Roger-Melo
