### ISSUE TITLE
Resumo da Aula Desenvolvendo um popup da etapa 05

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [roger-melo-treinamentos/curso-de-js-roger-melo#7095]
## Desenvolvendo um popup
```js
const button = document.querySelector('button')
const popup = document.querySelector('.popup-wrapper')

button.addEventListener('click', () =>{
  popup.style.display = 'block'
})

popup.addEventListener('click', event => {
  const mouseClickedElement = event.target.classList[0]
  console.log(mouseClickedElement)
  const classNames = ['popup-wrapper', 'popup-close', 'popup-link']

  const shouldClosedPopup = classNames.some(className => className === mouseClickedElement)

  if(shouldClosedPopup){
    popup.style.display = 'none'
  }
})
```

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css">
  <title>Desenvolvendo um popup</title>
</head>
<body>
  <button>Clique Aqui</button>

  <div class="popup-wrapper">
    <div class="popup">
      <div class="popup-close">X</div>

      <div class="popup-content">
        <h2>Popup de Teste</h2>
        <p>O criador do popup foi Ethan Zuckerman</p>
        <a href="#" class="popup-link">Saiba Mais</a>
      </div>
    </div>
  </div>

  <script src="app.js"></script>
</body>
</html>
```

```css
* {
  box-sizing: border-box;
}

button {
  display: block;
  margin: 20px auto;
  background: crimson;
  color: white;
  border: 0;
  cursor: pointer;
  padding: 6px 10px;
}

.popup-wrapper {
  display: none;
  background: rgba(0, 0, 0, .5);
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.popup {
  font-family: arial;
  text-align: center;
  width: 100%;
  max-width: 300px;
  margin: 10% auto;
  padding: 20px;
  background: white;
  position: relative;
}

.popup a {
  color: white;
  cursor: pointer;
  padding: 6px 10px;
  text-decoration: none;
  background: crimson;
}

.popup-close {
  position: absolute;
  top: 5px;
  right: 10px;
  cursor:pointer;
}
```
