### ISSUE TITLE
Resumo da Aula 02-02 da etapa 06

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [roger-melo-treinamentos/curso-de-js-roger-melo#7145]
## Validação básica de formulários
```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testUsername = username => ^[a-zA-Z]{6,12}$.test(username)

form.addEventListener('submit', event = {
  event.preventDefault()  // No envio desse form eu estou impendindo que os dados sejam enviados para o servidor e que a página seja recarregada

  const isAValidUsername = testUsername( event.target.username.value)
  
  if(isAValidUsername){
    feedback.textContent = 'username válido'
    return
  }

  feedback.textContent = 'o username deve conter entre 6 a 12 caracteres e deve conter apenas letras'
})
```
 O evento keyup esse evento vai executar uma função de callback toda vez que a tecla pressionada for liberada, através da liberação das teclas.
```js
form.username.addEventListener('keyup', event = {

  const isAValidUsername = testUsername(event.target.value)
  console.log(event)
  if (isAValidUsername) {
    form.username.setAttribute('class', 'success')
    return
  }

  form.username.setAttribute('class', 'error')
})
```
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>Testando padrões de Regex</title>
</head>
<body>
  <h1>Testando padrões de Regex</h1>
  
  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
    <p class="feedback"></p>
  </form>
  <script src="app.js"></script>
</body>
</html>
```
```css
body{
  background: #eee;
}

h1{
 text-align: center;
}

form{
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}

.success {
  border: 2px solid green;
}

.error {
  border: 2px solid red;
}
```
