### ISSUE TITLE
Resumo da Aula 02-03  da etapa 06

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [roger-melo-treinamentos/curso-de-js-roger-melo#7156]
## Eventos do teclado

```js
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')


form.addEventListener('submit', event => {
  event.preventDefault() // No envio desse form eu estou impendindo que os dados sejam enviados para o servidor e que a página seja recarregada

  const username = event.target.username.value
  const usernameRegex = /^[a-zA-Z]{6,12}$/
  const isAValidUsername = usernameRegex.test(username)
  
  if(isAValidUsername){
    feedback.textContent = 'username válido'
    return
  }

  feedback.textContent = 'o username deve conter entre 6 a 12 caracteres e deve conter apenas letras'
})
```
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>Eventos do teclado</title>
</head>
<body>
  <h1>Eventos do teclado</h1>
  
  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
    <p class="feedback"></p>
  </form>
  
  <script src="app.js"></script>
</body>
</html>
```
```css
body{
  background: #eee;
}

h1{
 text-align: center;
}

form{
  max-width: 200px;
  margin: 40px auto;
  background: white;
  padding: 10px;
}

input, button {
  display: block;
  margin: 10px auto;
  padding: 4px;
}
```
