### ISSUE TITLE
Resumo da Aula 02-02 da etapa 10

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [roger-melo-treinamentos/curso-de-js-roger-melo#7399]
## Construindo um relógio digital

```js
const clockContainer = document.querySelector('.clock-container')

const updateClock = () => {
  const present = new Date()
  const hours = present.getHours()
  const minutes = present.getMinutes()
  const seconds = present.getSeconds()

  const clockHTML = `
  <span>${String(hours).length === 1 ? `0${hours}` : hours}</span> :
  <span>${String(minutes).length === 1 ? `0${minutes}` : minutes}</span> :
  <span>${String(seconds).length === 1 ? `0${seconds}` : seconds}</span>
  `

  clockContainer.innerHTML = clockHTML
}

setInterval(updateClock, 1000)
```

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="./style.css">
  <title>Construindo um Relógio Digital</title>
</head>
<body>
  <div class="clock-container"></div>

  <script src="app.js"></script>
</body>
</html>
```

```css
body {
  background-color: #212121;
}

.clock-container {
  font-size: 4em;
  text-align: center;
  margin: 200px auto 0;
  color: #fff;
  font-family: Arial, Helvetica, sans-serif;
}

.clock-container span {
  padding: 20px;
  background: #006ce6;
  border-radius: 10px;
}
```
