### ISSUE TITLE
Resumo da Aula Desenvolvendo um popup - Aula 04-04 + exercícios da etapa 05 

### ISSUE THREAD

**Issue by gustavo-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#7808]
### Desenvolvendo um popup - Aula 04-04

O tão famigerado POPUP que vem pra atasanar as pessoas, como o exemplo abaixo denota, o mesmo não é tão simples de se fazer, porém a titulo de aprendizado ele utlizida de varios elementos mais avançados em relação a eventos do DOM, como a manipulação do CSS das classes.

### EX:
```js

const button = document.querySelector('button')
const popup = document.querySelector('.popup-wrapper')

button.addEventListener('click', () => {
  popup.style.display = 'block'
  console.log('clicou')
})

popup.addEventListener('click', (event) => {
  const clicado = event.target.classList[0]
  const classNames = ['popup-close', 'popup-wrapper', 'popup-link']
  const shpuldClosePopup = classNames.some(classNames => classNames === clicado)
  if (shpuldClosePopup) {
    popup.style.display = 'none'
  }
})

```
```css
* {
  box-sizing: border-box;
}

button {
  display: block;
  margin: 20px auto;
  background: crimson;
  color: white;
  border: 0;
  cursor: pointer;
  padding: 6px 10px;
}

.popup-wrapper {
  display: none;
  background: rgba(0, 0, 0, .5);
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.popup {
  font-family: arial;
  text-align: center;
  width: 100%;
  max-width: 300px;
  margin: 10% auto;
  padding: 20px;
  background: white;
  position: relative;
}

.popup a {
  color: white;
  border: 0;
  cursor: pointer;
  padding: 6px 10px;
  text-decoration: none;
  background: crimson;
}

.popup-close {
  position: absolute;
  top: 5px;
  right: 10px;
  cursor: pointer;
}

```

### EXERCICIOS
```js
/*
  01

  - Faça com que ao clicar em um dos elementos dentro da div, a mensagem
    'Clicou na div.' não seja exibida no console.
*/

const div = document.querySelector('div')
const elementsInsideDiv = Array.from(div.children)
const h2 = document.querySelector('h2')

elementsInsideDiv.forEach(element => {
  element.addEventListener('click', (event) => {
    h2.innerText = `Clicou no ${element.nodeName.toLocaleUpperCase()}, filho da div`
    event.stopPropagation()
  })

})

div.addEventListener('click', () => {
  console.log('Clicou na div.')
})

/*
  02

  - No código acima, faça com que quando um filho da div for clicado, a mensagem
    exibida no console seja "Clicou no NOME_DA_TAG_COM_LETRAS_MINÚSCULAS, filho
    da div.".
*/

/*
  03

  - No index.html, abaixo da div sem classe, insira um h2;
  - Faça com que a mensagem de clique na div e a mensagem de clique em algum
    filho da div, ao invés de ser exibida no console, seja inserida neste h2.
*/

/*
  04

  - Faça com que quando o texto do h2 for copiado, a mensagem "Texto copiado!"
    seja exibida no console.
*/

h2.addEventListener('copy', () => {
  console.log("Texto copiado !")
})

/*
  05

  - Faça com que o movimento do mouse dentro da div com a classe "egg" substitua
    o texto que ela tem por
    "Eixo X: COORDENADA_EIXO_X | Eixo Y: COORDENADA_EIXO_Y".
*/
const egg = document.querySelector('.egg')

egg.addEventListener('mousemove', (event) => {
  egg.innerText = `Eixo X: ${event.offsetX} | Eixo Y: ${event.offsetY}`
})

/*
  06

  - Modifique a cor do ovo para "lightgoldenrodyellow" quando o botão for
    clicado.
*/

const button = document.querySelector('button')

button.addEventListener('click', () => {
  egg.style.background = 'lightgoldenrodyellow'
})


/*
  07

  - Se o array de pessoas abaixo conter, no mínimo, um(a) Front-end developer,
    exiba a mensagem abaixo no console.

    "O array people contém, no mínimo, um(a) Front-end developer."
*/

const people = [
  { id: 1, name: 'Pedro Henrique', profession: 'Dentista' },
  { id: 2, name: 'Fábio Alexandre', profession: 'Físico' },
  { id: 3, name: 'Thiago Ferreira', profession: 'Veterinário' },
  { id: 4, name: 'Marcelo Antonio', profession: 'Matemático' },
  { id: 5, name: 'Camilla Midori', profession: 'Engenheira Civil' },
  { id: 6, name: 'Gustavo D\'Aqui', profession: 'Gerente de Marketing' },
  { id: 7, name: 'Ana Paula', profession: 'Front-end developer' },
  { id: 8, name: 'Matheus Manucci', profession: 'Piloto' },
  { id: 9, name: 'Hamilton Silva', profession: 'Advogado' }
]

const searchPeople = people.some((people) => people.profession.includes("Front-end developer"))

if (searchPeople) {
  console.log("O array people contém, no mínimo, um(a) Front-end developer.")
}



```
